## Numerical Computing with Python and Numpy

In [2]:
kanto = [73, 67, 43]
johno = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

In [3]:
w1 = 0.3
w2 = 0.2
w3 = 0.5
weights = [w1, w2, w3]

In [4]:
def crop_yield(region, weights):
    result = 0
    for x,  w in zip(region, weights):
        # print(w)
        result += x * w
        # print(type(x), type(w))
    return result

In [5]:
crop_yield(kanto, weights)

56.8

In [6]:
import numpy as np

In [7]:
kanto = np.array([73, 67, 43])

In [8]:
kanto

array([73, 67, 43])

In [9]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [10]:
weights = np.array([w1, w2, w3])

In [11]:
# weights = np.array([w1, w2, w3])

In [12]:
weights

array([0.3, 0.2, 0.5])

In [13]:
type(kanto)

numpy.ndarray

In [14]:
type(weights)

numpy.ndarray

In [15]:
weights[0]

0.3

In [16]:
weights[1]

0.2

In [17]:
weights[2]

0.5

In [18]:
np.dot(kanto, weights)

56.8

In [19]:
(kanto * weights).sum()
# (kanto * weights)

56.8

In [20]:
arr1 = np.array([1, 2, 3])

In [21]:
arr1.sum()

6

In [22]:
arr2 = np.array([4, 5, 6])

In [23]:
arr2.sum()

15

In [24]:
print(np.dot(arr1, arr2))

32


In [25]:
(arr1 * arr2).sum()

32

In [26]:
arr1.sum()

6

In [27]:
arr2.sum()

15

In [28]:
arr1 = list(range(1000000))

In [29]:
arr2 = list(range(1000000, 2000000))

In [30]:
#numpy arrays
arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [31]:
%%time
result = 0
for x1, x2 in zip(arr1, arr2):
    result += x1+x2
result

CPU times: total: 297 ms
Wall time: 633 ms


1999999000000

In [32]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 2.59 ms


-1942957984

In [33]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])

In [34]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [35]:
climate_data.shape

(5, 3)

In [36]:
weights.shape

(3,)

In [37]:
arr3 = np.array([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19.5]]])

In [38]:
arr3.shape

(2, 2, 3)

In [39]:
arr3

array([[[11. , 12. , 13. ],
        [13. , 14. , 15. ]],

       [[15. , 16. , 17. ],
        [17. , 18. , 19.5]]])

In [40]:
weights.dtype

dtype('float64')

In [41]:
climate_data.dtype

dtype('int32')

In [42]:
arr3.dtype

dtype('float64')

In [43]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [44]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [45]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv',
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1bbd7c26550>)

In [46]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [47]:
climate_data.shape

(10000, 3)

In [48]:
weights = np.array([0.3, 0.2, 0.5])

In [49]:
yields = climate_data @ weights

In [50]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [51]:
yields.shape

(10000,)

In [52]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [53]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [54]:
climate_results.shape

(10000, 4)

In [55]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [56]:
demo = np.arange(6)

In [57]:
demo

array([0, 1, 2, 3, 4, 5])

In [58]:
np.savetxt('climate_results.txt',
            climate_results,
            fmt='%.2f',
            delimiter=',',
            header='temperature,rainfall,humidity,yeild_apples',
            comments='')

In [59]:
np.__version__

'1.24.3'

In [60]:
type(demo)

numpy.ndarray

In [61]:
demo.dtype

dtype('int32')

In [62]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [63]:
# given tuple as input to np.array fn
tpl_into_arr = np.array((1,2,3))

In [64]:
tpl_into_arr

array([1, 2, 3])

In [65]:
tpl_into_arr.ndim

1

In [66]:
# 0-D array
var_into_arr = np.array(42)

In [67]:
var_into_arr

array(42)

In [68]:
var_into_arr.ndim

0

In [69]:
type(var_into_arr)

numpy.ndarray

In [70]:
var_into_arr.dtype

dtype('int32')

In [71]:
help(np.mat)

Help on function asmatrix in module numpy:

asmatrix(data, dtype=None)
    Interpret the input as a matrix.
    
    Unlike `matrix`, `asmatrix` does not make a copy if the input is already
    a matrix or an ndarray.  Equivalent to ``matrix(data, copy=False)``.
    
    Parameters
    ----------
    data : array_like
        Input data.
    dtype : data-type
       Data-type of the output matrix.
    
    Returns
    -------
    mat : matrix
        `data` interpreted as a matrix.
    
    Examples
    --------
    >>> x = np.array([[1, 2], [3, 4]])
    
    >>> m = np.asmatrix(x)
    
    >>> x[0,0] = 5
    
    >>> m
    matrix([[5, 2],
            [3, 4]])



In [72]:
# 2-D array
x = np.array([[0, 2], [3, 4]])

In [73]:
x

array([[0, 2],
       [3, 4]])

In [74]:
m = np.asmatrix(x)

In [75]:
x[0,0] = 1

In [76]:
m.ndim

2

In [77]:
x.ndim

2

In [78]:
# 3-D array
three_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [79]:
three_arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [80]:
three_arr.ndim

3

In [81]:
# if you want to set minimum dimension of array then pass ndmin attribute to np.array([], ndim=n) , replace n with you minimum dimension number
# like arr = np.array([1, 2, 3, 4], ndim=2

In [82]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim, a)
print(b.ndim, b[1]+b[2])
print(c.ndim, c[0, 1] + c[1, 1], c[0]+c[1, 1], c[1, -1])
print(d.ndim, d[0, 1, 1])

0 42
1 5
2 7 [6 7 8] 6
3 5


In [83]:
a = np.array(42, ndmin=3)
print(a)
print(a.ndim)

[[[42]]]
3


In [84]:
a = np.arange(7)

In [85]:
a

array([0, 1, 2, 3, 4, 5, 6])

In [86]:
a[::2]

array([0, 2, 4, 6])

In [87]:
a[1:5]

array([1, 2, 3, 4])

In [88]:
a[4:]

array([4, 5, 6])

In [89]:
a[:4]

array([0, 1, 2, 3])

In [90]:
a[-3:-1]

array([4, 5])

In [91]:
a[1:5:2]

array([1, 3])

In [92]:
a[::2]

array([0, 2, 4, 6])

In [93]:
c[1, 1:4]

array([5, 6])

In [94]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])
print(arr[0:2, 1:4])

[3 8]
[[2 3 4]
 [7 8 9]]


In [95]:
arr = np.array(['apple', 'banana', 'cherry'])

In [96]:
arr.dtype

dtype('<U6')

In [97]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [98]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('int')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [99]:
arr = np.array([1, 0, 4])
newarr = arr.astype(bool)
print(arr)
print(newarr)

[1 0 4]
[ True False  True]


In [100]:
arr = np.arange(6)
x = arr.copy()
x[0] = 8
print(arr)
print(x)

[0 1 2 3 4 5]
[8 1 2 3 4 5]


In [101]:
arr = np.arange(5)
y = arr.view()
y[0] = 8
print(arr)
print(y)

[8 1 2 3 4]
[8 1 2 3 4]


In [102]:
arr = np.arange(5)
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[0 1 2 3 4]


In [103]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 4)

print(newarr) 

[[1 2 3 4]
 [5 6 7 8]]


In [106]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [107]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

oldarr = newarr.reshape(-1)

print(oldarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]


In [108]:
newarr = np.arange(9)
print(np.flip(newarr))

[8 7 6 5 4 3 2 1 0]


In [109]:
for item in arr:
    print(item)

1
2
3
4
5
6
7
8


In [110]:
arr = np.arange(6)
newarr = arr.reshape(2, 3)
# print(newarr)

# for x in newarr:
    # print(x)
    
for x in newarr:
    for y in x:
        print(y)
        
for x in np.nditer(newarr):
    print(x)

0
1
2
3
4
5
0
1
2
3
4
5


In [111]:
arr = np.arange(12)
newarr = arr.reshape(2, 2, -1)
# print(newarr)

for x in newarr:
    for y in x:
        for z in y:
            print(z)
            
for x in np.nditer(newarr):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11
0
1
2
3
4
5
6
7
8
9
10
11


In [112]:
arr = np.arange(3)

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'0'
b'1'
b'2'


In [113]:
arr = np.arange(8)

newarr = arr.reshape(2, 4)

# print(newarr)

for x in np.nditer(newarr[:, ::2]):
    print(x)

0
2
4
6


In [114]:
arr = np.arange(3)

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 0
(1,) 1
(2,) 2


In [115]:
arr = np.arange(8)

newarr = arr.reshape(2, 4)

print(newarr)

[[0 1 2 3]
 [4 5 6 7]]


In [116]:
arr1 = np.arange(3)
arr2 = np.arange(3, 6)

# below both statements are same because default axis=0
arr = np.concatenate((arr1, arr2))
# arr = np.concatenate((arr1, arr2), axis = 0)

print(arr)

[0 1 2 3 4 5]


In [117]:
arr1 = np.arange(1,5)
newarr1 = arr1.reshape(2,2)
arr2 = np.arange(5, 9)
newarr2 = arr2.reshape(2,2)

print("arr1 : ",newarr1)
print("arr2 : ", newarr2)

# concatenate arrs by axis = 1
arr = np.concatenate((newarr1, newarr2), axis=1)
print("new concatenate arr : ", arr)

# concatenate arrs by axis = 0 or default axis is 0
arr = np.concatenate((newarr1, newarr2))
print("new concatenate arr : ", arr)


arr1 :  [[1 2]
 [3 4]]
arr2 :  [[5 6]
 [7 8]]
new concatenate arr :  [[1 2 5 6]
 [3 4 7 8]]
new concatenate arr :  [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [118]:
arr1 = np.arange(1,4)
# newarr1 = arr1.reshape(2,2)
arr2 = np.arange(4, 7)
# newarr2 = arr2.reshape(2,2)
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [119]:
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)

# NumPy provides a helper function: hstack() to 
# stack along row

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [120]:
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)

# NumPy provides a helper function: vstack() to
# stack along column

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [121]:
arr1 = np.arange(1, 4)
arr2 = np.arange(4, 7)

# Numpy provides a helper function: dstack() to
# stack along height, which is the same as depth

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [122]:
arr = np.arange(1, 7)

# split the array in 3 parts:
newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [123]:
arr = np.arange(1, 7)

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [124]:
arr = np.arange(1, 7)

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [125]:
arr = np.arange(1, 19)

arr1 = arr.reshape(6, 3)

# print(arr1)

newarr = np.array_split(arr1, 3)
print(newarr)

newarr = np.array_split(arr1, 3, axis=1)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [126]:
arr = np.arange(1, 19)

arr1 = arr.reshape(6, 3)

print(arr1)

newarr = np.hsplit(arr1, 3)

print(newarr)

# similar alternates to vstack() and dstack() are
# available as vsplit() and dsplit()

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [127]:
# find indexes where value at 
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [128]:
# odd number array
arr = np.arange(1, 9)
x = np.where(arr%2 == 0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [129]:
# even number array
arr = np.arange(1, 9)
# both below statements are same
# x = np.where(arr%2 != 0)
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6], dtype=int64),)


In [130]:
arr = np.arange(6, 10)
x = np.searchsorted(arr, 7)

print(x)

1


In [131]:
arr = np.array([6, 7, 8, 9, 10, 7, 10])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [132]:
arr = np.array([1, 2, 3, 4, 9, 8, 1, 4, 7, 6])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 3 8]


In [133]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [134]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [135]:
# Getting some elements out of an existing array and creating a new array out of them is called filtering.

# In NumPy, you filter an array using a boolean index list.

# A boolean index list is a list of booleans corresponding to indexes in the array.

arr = np.array([41, 42, 43, 44, 45])

x = [True, False, True, False, True]

newarr = arr[x]

print(newarr)

[41 43 45]


In [136]:
arr = np.array([41, 42, 43, 44, 45])

filter_arr = []

for ele in arr:
    if ele > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
        
newarr = arr[filter_arr]

print("filter arr : ", newarr)
print("arr : ", arr)

filter arr :  [43 44 45]
arr :  [41 42 43 44 45]


In [137]:
arr = np.arange(1, 7)
filter_arr = []

for ele in arr:
    if ele%2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
    
newarr = arr[filter_arr]

print("filter arr : ", newarr)
print("arr : ", arr)

filter arr :  [2 4 6]
arr :  [1 2 3 4 5 6]


In [138]:
# Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(newarr)

[43 44]


In [139]:
# Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


In [140]:
x = ["one", "two"]
x[1] = "three"
x

['one', 'three']